### ISSUE TITLE
UI issue PCF Ops Manager > Verbose in 'LogMessage' event typo

### ISSUE THREAD

**Issue by stacykor** [pivotal-cf/docs-sumologic#6]
Help text next for Cloud Foundry Settings - Verbose in 'LogMessage' Event is wrong. 

current version:
If is not checked, the 'LogMessage' will contain ONLY the fields 'tiemstamp', 'cf_app_guid', 'Msg'

should be 
If is not checked, the 'LogMessage' will contain ONLY the fields 'timestamp', 'cf_app_guid', 'Msg'

**Comment by jncd** [comment]
It looks like this had been fixed.
